### ISSUE TITLE
Path Separator Issue when generating versions.html

### ISSUE THREAD

**Issue by riedgar-ms** [Holzhaus/sphinx-multiversion#31]
Following the documentation, I've created a `versions.html` file with the following content:
```html
{%- if current_version %}
<div class="rst-versions" data-toggle="rst-versions" role="note" aria-label="versions">
  <span class="rst-current-version" data-toggle="rst-current-version">
    <span class="fa fa-book"> Other Versions</span>
    v: {{ current_version.name }}
    <span class="fa fa-caret-down"></span>
  </span>
  <div class="rst-other-versions">
    {%- if versions.tags %}
    <dl>
      <dt>Tags</dt>
      {%- for item in versions.tags %}
      <dd><a href="{{ item.url }}">{{ item.name }}</a></dd>
      {%- endfor %}
    </dl>
    {%- endif %}
    {%- if versions.branches %}
    <dl>
      <dt>Branches</dt>
      {%- for item in versions.branches %}
      <dd><a href="{{ item.url }}">{{ item.name }}</a></dd>
      {%- endfor %}
    </dl>
    {%- endif %}
  </div>
</div>
{%- endif %}
```
I force this file to be rendered by including it in the `html_additional_pages` dictionary.

When I run `sphinx-multiversion` on a Windows machine, I've noticed that the resultant file looks like:
```html
<div class="rst-versions" data-toggle="rst-versions" role="note" aria-label="versions">
  <span class="rst-current-version" data-toggle="rst-current-version">
    <span class="fa fa-book"> Other Versions</span>
    v: riedgar-ms/versioned-docs-01
    <span class="fa fa-caret-down"></span>
  </span>
  <div class="rst-other-versions">
    <dl>
      <dt>Branches</dt>
      <dd><a href="..\../master/index.html">master</a></dd>
      <dd><a href="versions.html">riedgar-ms/versioned-docs-01</a></dd>
    </dl>
  </div>
</div>
```
I don't think that the `\` in the path to the `master` branch is going to play nicely when deployed to a webserver. There is a similar issue in the path in the 'other' `versions.html` file.

**Comment by Holzhaus** [comment]
It's probably this call to `os.path.join`: https://github.com/Holzhaus/sphinx-multiversion/blob/master/sphinx_multiversion/sphinx.py#L114

Can you check if replacing it with `posixpath.join` fixes the issue? I don't use Windows and can't check myself.

**Comment by riedgar-ms** [comment]
That has fixed one of the issues:
```html
      <dt>Branches</dt>
      <dd><a href="../../master/index.html">master</a></dd>
      <dd><a href="versions.html">riedgar-ms/versioned-docs-01</a></dd>
```

However, there's still a problem in the 'other' copy of the file:
```html
      <dt>Branches</dt>
      <dd><a href="versions.html">master</a></dd>
      <dd><a href="../riedgar-ms\versioned-docs-01/index.html">riedgar-ms/versioned-docs-01</a></dd>
```
Note that this backslash is in the name of the git branch.

**Comment by Holzhaus** [comment]
Weird. Can you check if #32 fixes the issue? If not, can you please post the output of `--dump-metadata`?

**Comment by riedgar-ms** [comment]
That failed:
```
writing additional pages...  index versionsfailed

Theme error:
An error happened in rendering the page versions.
Reason: ValueError("'C:\\\\Users\\\\riedgar\\\\source\\\\repos\\\\fairlearn\\\\build\\\\html\\\\riedgar-ms/versioned-docs-01' does not start with 'C:\\\\Users\\\\riedgar\\\\source\\\\repos\\\\fairlearn\\\\build\\\\html'",)
Traceback (most recent call last):
  File "C:\Users\riedgar\AppData\Local\Continuum\miniconda3\envs\py-36\Scripts\sphinx-multiversion-script.py", line 33, in <module>
    sys.exit(load_entry_point('sphinx-multiversion', 'console_scripts', 'sphinx-multiversion')())
  File "c:\users\riedgar\source\repos\sphinx-multiversion\sphinx_multiversion\main.py", line 302, in main
    subprocess.check_call(cmd, cwd=current_cwd)
  File "c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('c:\\users\\riedgar\\appdata\\local\\continuum\\miniconda3\\envs\\py-36\\python.exe', '-m', 'sphinx', '-D', 'smv_metadata_path=C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmppn0yo8lp\\versions.json', '-D', 'smv_current_version=master', '-c', 'C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs', 'C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmppn0yo8lp\\b4c07dbcac0c24a3531653718fc63e1ba6e1a2cd\\docs', 'C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\master')' returned non-zero exit status 2.
```

Running with `--dump-metadata`:
```
{
  "master": {
    "name": "master",
    "version": "",
    "release": "0.4.7.dev0",
    "is_released": false,
    "source": "heads",
    "creatordate": "2020-08-07 07:45:20 -0700",
    "basedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpiloxyxe6\\b4c07dbcac0c24a3531653718fc63e1ba6e1a2cd",
    "sourcedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpiloxyxe6\\b4c07dbcac0c24a3531653718fc63e1ba6e1a2cd\\docs",
    "outputdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\master",
    "confdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs",
    "docnames": [
      "api_reference/fairlearn.datasets",
      "api_reference/index",
      "contributor_guide/developer_call_notes/2020_05_07",
      "user_guide/index",
      "contributor_guide/ways_to_contribute",
      "user_guide/assessment",
      "user_guide/fairness_in_machine_learning",
      "user_guide/further_resources",
      "about/index",
      "contributor_guide/developer_call_notes/2020_06_11",
      "api_reference/fairlearn.reductions",
      "contributor_guide/fairlearn_proposals",
      "api_reference/fairlearn.metrics",
      "api_reference/fairlearn.widget",
      "contributor_guide/how_to_talk_about_fairness",
      "contributor_guide/fairlearn_repository_overview",
      "contributor_guide/index",
      "contributor_guide/developer_call_notes/index",
      "contributor_guide/developer_call_notes/2020_07_09",
      "quickstart",
      "contents",
      "api_reference/fairlearn.postprocessing",
      "contributor_guide/development_process",
      "contributor_guide/contributing_code",
      "user_guide/mitigation",
      "contributor_guide/contributing_example_notebooks",
      "faq"
    ]
  },
  "riedgar-ms/versioned-docs-01": {
    "name": "riedgar-ms/versioned-docs-01",
    "version": "",
    "release": "0.4.7.dev0",
    "is_released": false,
    "source": "heads",
    "creatordate": "2020-08-06 11:53:06 -0400",
    "basedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpiloxyxe6\\b81e0846129432568973e50b3fa89103680bd0f9",
    "sourcedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpiloxyxe6\\b81e0846129432568973e50b3fa89103680bd0f9\\docs",
    "outputdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\riedgar-ms/versioned-docs-01",
    "confdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs",
    "docnames": [
      "api_reference/fairlearn.datasets",
      "api_reference/index",
      "contributor_guide/developer_call_notes/2020_05_07",
      "user_guide/index",
      "contributor_guide/ways_to_contribute",
      "user_guide/assessment",
      "user_guide/fairness_in_machine_learning",
      "user_guide/further_resources",
      "about/index",
      "contributor_guide/developer_call_notes/2020_06_11",
      "api_reference/fairlearn.reductions",
      "contributor_guide/fairlearn_proposals",
      "api_reference/fairlearn.metrics",
      "api_reference/fairlearn.widget",
      "contributor_guide/how_to_talk_about_fairness",
      "contributor_guide/fairlearn_repository_overview",
      "contributor_guide/index",
      "contributor_guide/developer_call_notes/index",
      "contributor_guide/developer_call_notes/2020_07_09",
      "quickstart",
      "contents",
      "api_reference/fairlearn.postprocessing",
      "contributor_guide/development_process",
      "contributor_guide/contributing_code",
      "user_guide/mitigation",
      "contributor_guide/contributing_example_notebooks",
      "faq"
    ]
  }
}
```

**Comment by riedgar-ms** [comment]
FYI, switching back to `master` the output of `--dump-metadata` is:
```
(py-36) PS C:\Users\riedgar\source\repos\fairlearn> sphinx-multiversion.exe docs build/html  --dump-metadata
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
C:\Users\riedgar\source\repos\fairlearn
C:\Users\riedgar\AppData\Local\Continuum\miniconda3\envs\py-36\Scripts
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\python36.zip
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\DLLs
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36
C:\Users\riedgar\AppData\Roaming\Python\Python36\site-packages
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages
c:\users\riedgar\source\repos\fairlearn
c:\users\riedgar\source\repos\sphinx-multiversion
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\Pythonwin
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
0.4.7.dev0
================================
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
C:\Users\riedgar\AppData\Local\Temp\tmpi4lcmi65\b4c07dbcac0c24a3531653718fc63e1ba6e1a2cd
C:\Users\riedgar\AppData\Local\Continuum\miniconda3\envs\py-36\Scripts
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\python36.zip
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\DLLs
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36
C:\Users\riedgar\AppData\Roaming\Python\Python36\site-packages
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages
c:\users\riedgar\source\repos\fairlearn
c:\users\riedgar\source\repos\sphinx-multiversion
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\Pythonwin
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
0.4.7.dev0
================================
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
C:\Users\riedgar\AppData\Local\Temp\tmpi4lcmi65\511e09ef7a438c755ea1666c3a3de312c6729d09
C:\Users\riedgar\AppData\Local\Continuum\miniconda3\envs\py-36\Scripts
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\python36.zip
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\DLLs
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36
C:\Users\riedgar\AppData\Roaming\Python\Python36\site-packages
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages
c:\users\riedgar\source\repos\fairlearn
c:\users\riedgar\source\repos\sphinx-multiversion
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\Pythonwin
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
0.4.7.dev0
================================
{
  "master": {
    "name": "master",
    "version": "",
    "release": "0.4.7.dev0",
    "is_released": false,
    "source": "heads",
    "creatordate": "2020-08-07 07:45:20 -0700",
    "basedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpi4lcmi65\\b4c07dbcac0c24a3531653718fc63e1ba6e1a2cd",
    "sourcedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpi4lcmi65\\b4c07dbcac0c24a3531653718fc63e1ba6e1a2cd\\docs",
    "outputdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\master",
    "confdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs",
    "docnames": [
      "contents",
      "quickstart",
      "api_reference/fairlearn.metrics",
      "api_reference/fairlearn.postprocessing",
      "user_guide/index",
      "user_guide/mitigation",
      "api_reference/fairlearn.widget",
      "contributor_guide/how_to_talk_about_fairness",
      "contributor_guide/index",
      "user_guide/fairness_in_machine_learning",
      "contributor_guide/developer_call_notes/2020_05_07",
      "user_guide/assessment",
      "contributor_guide/developer_call_notes/2020_07_09",
      "contributor_guide/development_process",
      "contributor_guide/developer_call_notes/index",
      "user_guide/further_resources",
      "api_reference/fairlearn.reductions",
      "contributor_guide/fairlearn_proposals",
      "about/index",
      "api_reference/index",
      "faq",
      "api_reference/fairlearn.datasets",
      "contributor_guide/developer_call_notes/2020_06_11",
      "contributor_guide/ways_to_contribute",
      "contributor_guide/contributing_example_notebooks",
      "contributor_guide/contributing_code",
      "contributor_guide/fairlearn_repository_overview"
    ]
  },
  "riedgar-ms/versioned-docs-01": {
    "name": "riedgar-ms/versioned-docs-01",
    "version": "",
    "release": "0.4.7.dev0",
    "is_released": false,
    "source": "heads",
    "creatordate": "2020-08-10 08:50:12 -0400",
    "basedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpi4lcmi65\\511e09ef7a438c755ea1666c3a3de312c6729d09",
    "sourcedir": "C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpi4lcmi65\\511e09ef7a438c755ea1666c3a3de312c6729d09\\docs",
    "outputdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\riedgar-ms/versioned-docs-01",
    "confdir": "C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs",
    "docnames": [
      "contents",
      "quickstart",
      "api_reference/fairlearn.metrics",
      "api_reference/fairlearn.postprocessing",
      "user_guide/index",
      "user_guide/mitigation",
      "api_reference/fairlearn.widget",
      "contributor_guide/how_to_talk_about_fairness",
      "contributor_guide/index",
      "user_guide/fairness_in_machine_learning",
      "contributor_guide/developer_call_notes/2020_05_07",
      "user_guide/assessment",
      "contributor_guide/developer_call_notes/2020_07_09",
      "contributor_guide/development_process",
      "contributor_guide/developer_call_notes/index",
      "user_guide/further_resources",
      "api_reference/fairlearn.reductions",
      "contributor_guide/fairlearn_proposals",
      "about/index",
      "api_reference/index",
      "faq",
      "api_reference/fairlearn.datasets",
      "contributor_guide/developer_call_notes/2020_06_11",
      "contributor_guide/ways_to_contribute",
      "contributor_guide/contributing_example_notebooks",
      "contributor_guide/contributing_code",
      "contributor_guide/fairlearn_repository_overview"
    ]
  }
}
```

**Comment by Holzhaus** [comment]
@riedgar-ms I was finally able to reproduce the issue after I added Windows builds on Travis CI and added some unittests. Can you check if #35 fixes the problem?

**Comment by riedgar-ms** [comment]
That seems to have fixed it, thanks!

**Comment by Holzhaus** [comment]
Great, then I'll merge that PR now and publish a new release soon.
