### ISSUE TITLE
Empty queue error when building doc

### ISSUE THREAD

**Issue by setiat** [Holzhaus/sphinx-multiversion#89]
```
poetry run sphinx-multiversion docs/source/ build
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/bin/sphinx-multiversion", line 5, in <module>
    from sphinx_multiversion import main
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/__init__.py", line 2, in <module>
    from .sphinx import setup
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/sphinx.py", line 9, in <module>
    from sphinx import config as sphinx_config
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx/config.py", line 22, in <module>
    from sphinx.util.i18n import format_date
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx/util/i18n.py", line 17, in <module>
    import babel.dates
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/__init__.py", line 20, in <module>
    from babel.core import UnknownLocaleError, Locale, default_locale, \
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/core.py", line 14, in <module>
    from babel import localedata
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/localedata.py", line 21, in <module>
    from babel._compat import pickle, string_types, abc
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/_compat.py", line 30, in <module>
    array_tobytes = array.array.tobytes
AttributeError: module 'array' has no attribute 'array'
Traceback (most recent call last):
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/bin/sphinx-multiversion", line 8, in <module>
    sys.exit(main())
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/main.py", line 182, in main
    config = load_sphinx_config(
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/main.py", line 86, in load_sphinx_config
    result = q.get_nowait()
  File "/opt/miniconda3/lib/python3.9/multiprocessing/queues.py", line 135, in get_nowait
    return self.get(False)
  File "/opt/miniconda3/lib/python3.9/multiprocessing/queues.py", line 116, in get
    raise Empty
_queue.Empty

(base) ndi-mb-107:ts-sphinx-doc-publish tarik.setia$ git tag -a "1.1"
(base) ndi-mb-107:ts-sphinx-doc-publish tarik.setia$ git push origin 1.1 
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 158 bytes | 79.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To tetra:tetrascience/ts-sphinx-doc-publish.git
 * [new tag]         1.1 -> 1.1
(base) ndi-mb-107:ts-sphinx-doc-publish tarik.setia$ poetry run sphinx-multiversion docs/source/ build
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/bin/sphinx-multiversion", line 5, in <module>
    from sphinx_multiversion import main
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/__init__.py", line 2, in <module>
    from .sphinx import setup
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/sphinx.py", line 9, in <module>
    from sphinx import config as sphinx_config
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx/config.py", line 22, in <module>
    from sphinx.util.i18n import format_date
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx/util/i18n.py", line 17, in <module>
    import babel.dates
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/__init__.py", line 20, in <module>
    from babel.core import UnknownLocaleError, Locale, default_locale, \
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/core.py", line 14, in <module>
    from babel import localedata
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/localedata.py", line 21, in <module>
    from babel._compat import pickle, string_types, abc
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/babel/_compat.py", line 30, in <module>
    array_tobytes = array.array.tobytes
AttributeError: module 'array' has no attribute 'array'
Traceback (most recent call last):
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/bin/sphinx-multiversion", line 8, in <module>
    sys.exit(main())
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/main.py", line 182, in main
    config = load_sphinx_config(
  File "/Users/tarik.setia/tetrascience/ts-sphinx-doc-publish/.venv/lib/python3.9/site-packages/sphinx_multiversion/main.py", line 86, in load_sphinx_config
    result = q.get_nowait()
  File "/opt/miniconda3/lib/python3.9/multiprocessing/queues.py", line 135, in get_nowait
    return self.get(False)
  File "/opt/miniconda3/lib/python3.9/multiprocessing/queues.py", line 116, in get
    raise Empty
_queue.Empty
```

**Comment by BurningEnlightenment** [comment]
Hi, can you provide us with a reprex (reproducing example) or if possible a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?
