### ISSUE TITLE
Can't fetch git history

### ISSUE THREAD

**Issue by amwps290** [Holzhaus/sphinx-multiversion#93]
when i use sphinx_gitstamp extension with sphinx-multiversion ,

```
Can't fetch git history for D:\sphinx\source/appendix.rst.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\sphinx-multiversion.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx_multiversion\main.py", line 338, in main
    subprocess.check_call(cmd, cwd=current_cwd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-R', '-m', 'sphinx', '-D', 'smv_metadata_path=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpb4xkpsm0\\versions.json', '-D', 'smv_current_version=1.0', '-c', 'D:\\sphinx\\YukonDoc\\doc\\source', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpb4xkpsm0\\041a1be80c024630d305ebd0de4ffea5094c942b\\doc\\source', 'D:\\sphinx\\YukonDoc\\doc\\build\\html\\1.0')' returned non-zero exit status 2.
```

the appendix.rst removed from recently commit.

**Comment by BurningEnlightenment** [comment]
Unless I'm misunderstanding something, I don't think that `sphinx_gitstamp` can work with `sphinx-multiversion` due to copying the sources into a non-git directory (see also #17).
